package co.edu.eam.ingesoft.distribuidos.cliente.gui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.awt.GridLayout;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.SocketException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;

import co.edu.eam.ingesoft.distribuidos.cliente.controlador.EntradaVideo;
import co.edu.eam.ingesoft.distribuidos.cliente.controlador.SalidaVideo;

/**
 *
 * @author MAO
 */
public class VentanaVideoLlamada extends javax.swing.JFrame implements Observer {

	/**
	 * Creates new form Ventana
	 */
	private Map<String, Integer> videoMap;
	private List<JLabel> videoList;
	Socket con;
	static ServerSocket serversock;

	public VentanaVideoLlamada() {		

		initComponents();
	}
	
	EntradaVideo entradaVideo;

	public VentanaVideoLlamada(EntradaVideo entradaVideo) {
		this.entradaVideo = entradaVideo;
		videoMap = new HashMap<>();
		videoList = new ArrayList<>();
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1VideoGrid = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1VideoGrid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

		javax.swing.GroupLayout jPanel1VideoGridLayout = new javax.swing.GroupLayout(jPanel1VideoGrid);
		jPanel1VideoGrid.setLayout(jPanel1VideoGridLayout);
		jPanel1VideoGridLayout.setHorizontalGroup(jPanel1VideoGridLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 171, Short.MAX_VALUE));
		jPanel1VideoGridLayout.setVerticalGroup(jPanel1VideoGridLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 146, Short.MAX_VALUE));

		jButton1.setText("INICIAR VIDEOLLAMADA");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(22, 22, 22)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel1VideoGrid, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addComponent(jButton1).addGap(10, 10, 10)))
						.addContainerGap(230, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(24, 24, 24)
						.addComponent(jPanel1VideoGrid, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(26, 26, 26).addComponent(jButton1).addContainerGap(80, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		// se inicia la video llamada en la pantalla 1x1
		int filas = 1;
		int columnas = 1;
		GridLayout grid = new GridLayout(filas, columnas);
		jPanel1VideoGrid.setLayout(grid);

		videoList = new ArrayList<>();

		videoList.clear();
		videoMap.clear();
		jPanel1VideoGrid.removeAll();

		for (int i = 0; i < filas; i++) {

			for (int j = 0; j < columnas; j++) {

				JLabel l = new JLabel();
				videoList.add(l);
				l.setHorizontalAlignment(SwingConstants.CENTER);
				l.setVerticalAlignment(SwingConstants.TOP);
				jPanel1VideoGrid.add(l);
				l.setText(i + "," + j);
				l.setSize(jPanel1VideoGrid.getWidth() / columnas, jPanel1VideoGrid.getHeight() / filas);
				l.setBorder(new LineBorder(Color.RED, 1));

			}
		}

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(VentanaVideoLlamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(VentanaVideoLlamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(VentanaVideoLlamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(VentanaVideoLlamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {

				new VentanaVideoLlamada().setVisible(true);

			}
		});

	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JPanel jPanel1VideoGrid;
	// End of variables declaration

	

	@Override
	public void update(Observable arg0, Object arg1) {
		
		byte[] data = ((DatagramPacket) arg1).getData();
		String ip = ((DatagramPacket) arg1).getAddress().getHostAddress();
		
		
		// -----ELEGIR PANEL-----
		if (!videoList.isEmpty()) {
			int idx = 0;
			if (videoMap.containsKey(ip)) {
				idx = videoMap.get(ip);
			} else {
				idx = videoMap.size();
				videoMap.put(ip, idx);
			}

			videoList.get(idx).setIcon(new ImageIcon(data));
			videoList.get(idx).setText(ip);
		}
		
	}

}
